# Generated by Django 3.2 on 2022-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='extra',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
