# Generated by Django 3.2 on 2022-10-31 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_certificates_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='degree',
            name='courses_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
