# Generated by Django 3.2 on 2022-11-02 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20221031_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
    ]
