# Generated by Django 3.2 on 2022-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20221102_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
